### ISSUE TITLE
Missing files for fault injection test

### ISSUE THREAD

**Issue by avanitanna** [vul337/PrIntFuzz#5]
Awesome research! I am trying to run your tool precisely as you describe it in your readme (same target kernel, same host kernel, set up using the one-click setup script). I ran the setup script successfully, patched the host KVM module, and verified that the `he` driver shows up in the VM. When I try to run the fault injection test (for USB, PCI, and I2C), I get lots of errors of the type
```
Traceback (most recent call last):
  File "/root/PrIntFuzz/scripts/python/qemu.py", line 121, in <module>
    qemu.process()
  File "/root/PrIntFuzz/scripts/python/qemu.py", line 114, in process
    output_file = open(self.extend_args.output, 'w') if self.extend_args.output \
FileNotFoundError: [Errno 2] No such file or directory: out/probe/drivers@bluetooth@bfusb.c/drivers_bluetooth_bfusb.txt

```
As far as I can tell, all modules that the script tries to analyze fail in this manner. Which step should generate these files? Is there a way I can generate them myself?

**Comment by ZheyuMa** [comment]
Sorry for the late reply, have you solved the problem yet?
